### PR TITLE
fix(gondel decorator): prevent duplicated events with multiple gondel…

### PR DESCRIPTION
**Pull request by janwidmer**
… core instances in different files

## Purpose of this pull request? 

* Bug fix

## What changes did you make?

use window to define a global state variable, if Core Events have been initialized.

## Does this pull request introduce a breaking change?

No

Closes https://github.com/namics/gondel/issues/48

### CODE REVIEW

**Comment by jantimon** [comment]
gondel already provides global variables:

gondel-globals_-_StackBlitz

instead of introducing a global variable without prefix es we should rather reuse `__gondelPluginEvents`  or adjust `__gondelPluginEvents` to provide this feature out of the box

**Comment by janbiasi** [comment]
And we should also type the `__gondelPluginEvents` 😄

**Comment by jantimon** [comment]
Hey @janbiasi I took a look together with @janwidmer to address the root of the problem and found a solution which looks promising (however it will introduce a small breaking change)

**Comment by janwidmer** [comment]
Will be done in new PR

**Pull request closed without merging**
