### PR TITLE
feat(core): fallback to classname as componentname

### PR DESCRIPTION
**Pull request by adriankremer**
To make it easier to spawn a component i want the ComponentName to be optional and to get the ClassName as default.

* Enhancement

## What changes did you make?

I made the componentName optional and invoked the className as default.

## Does this pull request introduce a breaking change?

no!

### CODE REVIEW

**Comment by jantimon** [comment]
Angular 1 did it that way but unfortunately it does not work after minification as `class Button` becomes `function a`

**Comment by adriankremer** [comment]
Damn thats right. The only way would be to do something like
```js
new Gondel({
  components: {
    componentA,
    componentB
  }
});
```
isnt it?

**Comment by jantimon** [comment]
Correct that would work but would probably be very hard to type with typescript

**Comment by janbiasi** [comment]
@jantimon I already talked with you about a possible solution by defining the component name as static property - metadata reflection isn't a possibility in our case since not every project uses gondel with typescript ... 

cc @adriankremer

**Comment by jantimon** [comment]
And I guess even if it would work the metadata would blow up the bundle size

**Pull request closed without merging**
