### PR TITLE
feat(react plugin): provide a factory function to connect Gondel and React

### PR DESCRIPTION
**Pull request by jantimon**
This enhancement will:
 - add a new util helper so we don't have to use generics anymore
 - stop mounted react apps when calling `stop` 
 - adds unit tests

The name `createGondelReactLoader` is still open for discussion - we could also turn it into a static function e.g. `GondelReactComponent.create`

### for default export:

```ts
const GondelReactLoaderComponent = createGondelReactLoader(() => import('./App'));
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent {
```

### for named export:

```ts
const GondelReactLoaderComponent = createGondelReactLoader(() => import('./App'), 'App');
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent {
```

### for default export:

```ts
const loader = () => import('./App');
@Component("Greeter")
class Greeter extends createGondelReactLoader(loader) {
```

### for named export:

```ts
const loader = () => import('./App');
@Component("Greeter")
class Greeter extends createGondelReactLoader(loader, 'App') {
```

### for default export:

```ts
@Component("Greeter")
class Greeter extends createGondelReactLoader(() => import('./App')) {
```

### for named export:

```ts
@Component("Greeter")
class Greeter extends createGondelReactLoader(() => import('./App'), 'App') {
```

### CODE REVIEW

**Comment by janbiasi** [comment]
Implication downside if we use a static function would be that we will loose the minification of `create` into eg. `c` (minified function name), that would be 5 characters per usage which could not get minified. Imo we can ignore these 5 characters as they won't blow up the bundle size compared to libraries or any other code we possibly have which isn't optimized for minification.

**Providing examples for the static version:**

## base syntax

### for default export:

```ts
const GondelReactLoaderComponent = GondelReactLoaderComponent.create(() => import('./App'));
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent {
```

### for named export:

```ts
const GondelReactLoaderComponent = GondelReactLoaderComponent.create(() => import('./App'), 'App');
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent {
```


## emphasize the loader

### for default export:

```ts
const loader = () => import('./App');
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent.create(loader) {
```

### for named export:

```ts
const loader = () => import('./App');
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent.create(loader, 'App') {
```


## compact syntax

### for default export:

```ts
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent.create(() => import('./App')) {
```

### for named export:

```ts
@Component("Greeter")
class Greeter extends GondelReactLoaderComponent.create(() => import('./App'), 'App') {
```

**Comment by jantimon** [comment]
@ernscht and @smollweide prefer `GondelReactLoaderComponent.create` too

**Comment by janbiasi** [comment]
@jantimon should we finalize this in this week? :)

**Comment by janwidmer** [comment]
would be cool, then I could update the examples.. :-)

**Pull request merged**
